### ISSUE TITLE
Make HACS compliant

### ISSUE THREAD

**Issue by partofthething** [partofthething/ha_skyfield#1]
Should be installable via the HACS. 

This was [requested in the forum](https://community.home-assistant.io/t/polar-plot-of-the-sun-moon-a-few-planets-and-the-solstices/151866).

Info here: https://hacs.xyz/

**Comment by partofthething** [comment]
Ok in 346298c824200ec I attempted this but have not yet tested.

**Comment by partofthething** [comment]
Looks like we need to make this a hassio docker image to make this happen. I still need to figure out how to do that.

**Comment by Repsionu** [comment]
Hassio is of high demand of course. Myself running HA in virtualenv and all works with manual install (except could out figure out additional options like constellations etc.)
Best, JR
PS Hope You figure out the dependencies stuff for hassio and HACS users :-)
Thanks :-)

**Comment by partofthething** [comment]
With https://github.com/partofthething/ha_skyfield/pull/3 I understand it works in Hassio now.

**Comment by kaosmagix** [comment]
> With #3 I understand it works in Hassio now.

Yes, you can add https://github.com/partofthething/ha_skyfield as a custom repository to HACS and install/update it from their

**Comment by partofthething** [comment]
Awesome.
