### ISSUE TITLE
Can't rotate image for my real nort positon..

### ISSUE THREAD

**Issue by fabHAgithub** [partofthething/ha_skyfield#11]
I need some HELP, please!!! :(
How to rotate the position of the N to the E, like in this pic?
![image](https://user-images.githubusercontent.com/85220859/146872934-8dfdbaea-e9a8-4996-8956-43f5e8c9a393.png)

my config in *cameras.yaml*

```
 - platform: ha_skyfield
   show_constellations: false
   north_up: true
   show_time: true
   show_legend: true
#   planet_list: true
```

**Comment by partofthething** [comment]
That would require a slight upgrade to the component. It's not supported yet by the current config options. I could add a more flexible option that allows you to specify any degree that you want to be up.

**Comment by fabHAgithub** [comment]
I got it. Great job you did.
Thanks for the reply, my friend. 💯

**Comment by partofthething** [comment]
If you want a quick work-around you can change [this line](https://github.com/partofthething/ha_skyfield/blob/bab0cc93c8479dc332353eb79566dcae635888ff/custom_components/ha_skyfield/bodies.py#L194) to

```
        ax.set_theta_zero_location("E", offset=0)
```

**Comment by fabHAgithub** [comment]
Okay.. Mesmerizing. 
I will try to change and send feedback.

**Comment by fabHAgithub** [comment]
![image](https://user-images.githubusercontent.com/85220859/146875666-1dcea63a-bc9c-4239-869e-86e16bc35ad3.png)
💯 It works, man!!! 
💯 Thank u 🥇 :)
💯 Love u s2
