### ISSUE TITLE
Switch from PNG to JPG to conserve bandwidth

### ISSUE THREAD

**Issue by linuxkidd** [partofthething/ha_skyfield#20]
For this project, using PNG doesn't provide valuable visual benefit over a more highly compressed format like JPG.

The bandwidth savings is especially important for remote observatories with limited connectivity options.

```
-rw-r--r-- 1 root root  47K Jan 19 16:59 skyfield.jpg
-rw-r--r-- 1 root root 111K Jan 19 17:03 skyfield.png
```

Additionally, `jpg` compression is generally easier to perform on low power systems like the single board, ARM computers.

**Comment by partofthething** [comment]
Seems reasonable. I usually assume the lossless compression of png ends up performing better than jpg for line graphics like this. But I'm happy to be wrong. Would be nice to get side-to-side screenshots. 

Before, I'm seeing 129 kB pngs coming down from the network console. 

After, looks like 49 kB jpgs. I see a few compression artifacts and stuff.

**Comment by linuxkidd** [comment]
Hi @partofthething -- you may be correct on the compression difficulty for line art - I was applying experience from the AllSky project ( png takes a lot more time on a Pi than jpg for allsky photos ).

Upon very close inspection, I do see some compression artifacts.  I think making it a configurable option makes the most sense.

Comparison images:

### PNG format
![skyfield](https://user-images.githubusercontent.com/6115364/213742292-b5471c75-81b8-4128-835d-e1608c11d22c.png)

### JPG format
![skyfield](https://user-images.githubusercontent.com/6115364/213742363-568d92c3-0617-4c67-b81d-117d7594c62a.jpg)

Over the wire transfer size differences observed:
**PNG:** 216.91 kB
**JPG:** 89.95 kB

I've refactored the code in the PR.  Let me know what you think.
